apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: cluster-runnerdeploy
spec:
  replicas: 1
  template:
    spec:
      repository: https://github.com/d4v5he/gh_arc.git
